### PR TITLE
Two minor fixing about syslog db schema

### PR DESCRIPTION
**Pull request by ddb4github**
* Fixed: Remove duplicate index 'seq' from syslog_logs table;
 * Fixed: Sync 'syslog' table schema cross Traditional/Partitioned mode

### CODE REVIEW

**Comment by TheWitness** [comment]
I changed the logtime back to a TIMESTAMP as it's a TIMESTAMP.  If your version still has it as a DATETIME, update your upgrade script.

**Comment by ddb4github** [comment]
> I changed the logtime back to a TIMESTAMP as it's a TIMESTAMP. If your version still has it as a DATETIME, update your upgrade script.

MySQL Pre-8.0 does not support TIMESTAMP column in RANGE Partitioning, exception UNIX_TIMESTAMP function.
Need more diff to change:
 * Change column to timestamp
 * Change partition list generator to use seconds instead of days

**Comment by TheWitness** [comment]
Got it.  Get a new pull request together then.

**Comment by netniV** [comment]
Was there an update on this?

**Pull request merged**
