### PR TITLE
Update setup.php

### PR DESCRIPTION
**Pull request by bmfmancini**
Change Messege varchar from 1024 to 2048

```
+-------------+---------------------+------+-----+---------------------+----------------+
| Field       | Type                | Null | Key | Default             | Extra          |
+-------------+---------------------+------+-----+---------------------+----------------+
| facility_id | int(10) unsigned    | YES  | MUL | NULL                |                |
| priority_id | int(10) unsigned    | YES  | MUL | NULL                |                |
| program_id  | int(10) unsigned    | YES  | MUL | NULL                |                |
| host_id     | int(10) unsigned    | YES  | MUL | NULL                |                |
| logtime     | timestamp           | NO   | MUL | 0000-00-00 00:00:00 |                |
| message     | varchar(2048)       | NO   |     |                     |                |
| seq         | bigint(20) unsigned | NO   | PRI | NULL                | auto_increment |
+-------------+---------------------+------+-----+---------------------+----------------+
```

Install Tested
Uninstall tested

### CODE REVIEW

**Comment by netniV** [comment]
That pull request got pulled first... double pull for the loss?

**Comment by netniV** [comment]
To comments for the next request, don't forget to include upgrade settings and a changelog entry.

**Comment by bmfmancini** [comment]
Damn you beat me thats why I posted the second PR for the change log 

I thought I had got the upgrade settings let me double check

**Comment by netniV** [comment]
If you update your branch against the PR, it will update the PR.  You don't need to close and re-create it.  However, you do in your case because it was against master not develop.

**Pull request closed without merging**
